---
title: "histone_profiles"
output: html_document
date: "2024-01-25"
---


```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
```


```{r}
HISTONES = "C:/Users/sarahhp/OneDrive - Universitetet i Oslo/Projects/rnaseq/beige_rnaseq_jul22/31_leafcutter/histone_profile/new_TSS"
k4 = read.delim(file.path(HISTONES, "H3K4me3","H3K4me3_white_beige-10.profile.tab"), skip=1)
to_bins = function(colname){
  return (as.double(gsub("X","", colname)))
}

k4= pivot_longer(k4, 3:ncol(k4), names_to = "bin", names_transform = to_bins, values_to = "enrichment" )
tail(k4)
k4=filter(k4, !is.na(enrichment))
colnames(k4) = c("Context","TSS_set","bin","enrichment")
k4 = mutate(k4, distance = bin*10-2000)
head(k4)

```


```{r}
k4$Context = factor(k4$Context, levels=c("White_Adi.","Beige_Adi."))
k4$TSS_set = factor(k4$TSS_set, levels = c("White_TSSs","Beige_TSSs","Non-sig_TSSs"))
ggplot(k4) + geom_line(aes(x=distance, y=enrichment, group=TSS_set, color=TSS_set, linetype=TSS_set), size=0.5) + 
  facet_wrap(~Context) + theme_classic(base_size=22) +scale_color_manual(values= c("dodgerblue","orange","black")) +
  scale_linetype_manual(values=c("solid","solid","dashed"))
ggsave(file.path(HISTONES, "H3K4me3","H3K4me3_white_beige-10.profile.R.pdf"), width=10, height=5)
#+ 
# geom_vline(aes(xintercept=-1000),  linetype="dashed") + geom_vline(aes(xintercept=2000), linetype="dashed")
```


## H3K27ac
```{r}
k27 = read.delim(file.path(HISTONES, "H3K27ac","H3K27ac_white_beige-10.profile.tab"), skip=1)
k27= pivot_longer(k27, 3:ncol(k27), names_to = "bin", names_transform = to_bins, values_to = "enrichment" )
tail(k27)
k27=filter(k27, !is.na(enrichment))
colnames(k27) = c("Context","TSS_set","bin","enrichment")
k27 = mutate(k27, distance = bin*10-2000)
head(k27)
```

```{r}
k27$Context = factor(k27$Context, levels=c("White_Adi.","Beige_Adi."))
k27$TSS_set = factor(k27$TSS_set, levels = c("White_TSSs","Beige_TSSs","Non-sig_TSSs"))
ggplot(k27) + geom_line(aes(x=distance, y=enrichment, group=TSS_set, color=TSS_set, linetype=TSS_set), size=0.5) + 
  facet_wrap(~Context) + theme_classic(base_size=22) +scale_color_manual(values= c("dodgerblue","orange","black")) +
  scale_linetype_manual(values=c("solid","solid","dashed")) + coord_cartesian(y=c(0,max(k27$enrichment)))
ggsave(file.path(HISTONES, "H3K27ac","H3K27ac_white_beige-10.profile.R.pdf"), width=10, height=5)
# + geom_hline(aes(yintercept=1)) + 
#  geom_vline(aes(xintercept=1000)) + geom_vline(aes(xintercept=-1000))
```

If we use the 1 enrichment threshold on the highest peak then a full +2000/-2000 is a good window


## H3K4me1

```{r}
me1 = read.delim(file.path(HISTONES, "H3K4me1/H3K4me1_white_beige-10.profile.tab"), skip=1)
me1= pivot_longer(me1, 3:ncol(me1), names_to = "bin", names_transform = to_bins, values_to = "enrichment" )
tail(me1)
me1=filter(me1, !is.na(enrichment))
colnames(me1) = c("Context","TSS_set","bin","enrichment")
me1 = mutate(me1, distance = bin*10-4000)
head(me1)
```

```{r}
me1$Context = factor(me1$Context, levels=c("White_Adi.","Beige_Adi."))
me1$TSS_set = factor(me1$TSS_set, levels = c("White_TSSs","Beige_TSSs","Non-sig_TSSs"))
ggplot(me1) + geom_line(aes(x=distance, y=enrichment, group=TSS_set, color=TSS_set, linetype=TSS_set), size=0.5) + 
  facet_wrap(~Context) + theme_classic(base_size=22) +scale_color_manual(values= c("dodgerblue","orange","black")) +
  scale_linetype_manual(values=c("solid","solid","dashed"))
ggsave(file.path(HISTONES, "H3K4me1","H3K4me1_white_beige-10.profile.R.pdf"), width=10, height=5)
#+ geom_hline(aes(yintercept=0.25)) + geom_vline(aes(xintercept=-250)) + 
 # geom_vline(aes(xintercept=500)) + geom_vline(aes(xintercept=-2000))
```

Should probably do the upstream and downstream windows... I wouldn't do stats on depletion levels, cos that depends on the noise/input and stuff.  But the most obvious one is +500 to 4000... or is it? upstream is the promoter, makes more sense



## H3K27me3

```{r}
pc = read.delim(file.path(HISTONES, "H3K27me3/H3K27me3_white_beige-10.profile.tab"), skip=1)
pc= pivot_longer(pc, 3:ncol(pc), names_to = "bin", names_transform = to_bins, values_to = "enrichment" )
tail(pc)
pc=filter(pc, !is.na(enrichment))
colnames(pc) = c("Context","TSS_set","bin","enrichment")
pc = mutate(pc, distance = bin*10-4000)
head(pc)
```

```{r}
pc$Context = factor(pc$Context, levels=c("White_Adi.","Beige_Adi."))
pc$TSS_set = factor(pc$TSS_set, levels = c("White_TSSs","Beige_TSSs","Non-sig_TSSs"))
ggplot(pc) + geom_line(aes(x=distance, y=enrichment, group=TSS_set, color=TSS_set, linetype=TSS_set), size=0.5) + 
  facet_wrap(~Context) + theme_classic(base_size=22) +scale_color_manual(values= c("dodgerblue","orange","black")) +
  scale_linetype_manual(values=c("solid","solid","dashed"))+  coord_cartesian(y=c(-1,1)) 
ggsave(file.path(HISTONES, "H3K27me3","H3K27me3_white_beige-10.profile.R.pdf"), width=10, height=5)

#+ geom_hline(aes(yintercept=0))
```


## PPARG

```{r}
pparg = read.delim(file.path(HISTONES, "PPARG/PPARG_white_beige-10.profile.tab"), skip=1)
pparg= pivot_longer(pparg, 3:ncol(pparg), names_to = "bin", names_transform = to_bins, values_to = "enrichment" )
tail(pparg)
pparg=filter(pparg, !is.na(enrichment))
colnames(pparg) = c("Context","TSS_set","bin","enrichment")
pparg = mutate(pparg, distance = bin*10-2000)
head(pparg)
```

```{r}
pparg$Context = factor(pparg$Context, levels=c("White_Adi.","Beige_Adi."))
pparg$TSS_set = factor(pparg$TSS_set, levels = c("White_TSSs","Beige_TSSs","Non-sig_TSSs"))
ggplot(pparg) + geom_line(aes(x=distance, y=enrichment, group=Context, color=Context, linetype=TSS_set), size=0.5) + 
  facet_wrap(~TSS_set) + theme_classic(base_size=22) +scale_color_manual(values= c("dodgerblue","orange","black")) +
  scale_linetype_manual(values=c("solid","solid","dashed"))+  coord_cartesian(y=c(0,12)) 
ggsave(file.path(HISTONES, "PPARG","PPARG_white_beige-10.profile.R.pdf"), width=15, height=5)

ggplot(pparg) + geom_line(aes(x=distance, y=enrichment, group=TSS_set, color=TSS_set, linetype=TSS_set), size=0.5) + 
  facet_wrap(~Context) + theme_classic(base_size=22) +scale_color_manual(values= c("dodgerblue","orange","black")) +
  scale_linetype_manual(values=c("solid","solid","dashed"))#+  coord_cartesian(y=c(-1,1)) 
#+ geom_hline(aes(yintercept=0))
```

##MED1
```{r}
med1 = read.delim(file.path(HISTONES, "MED1/MED1_white_beige-10.profile.tab"), skip=1)
med1= pivot_longer(med1, 3:ncol(med1), names_to = "bin", names_transform = to_bins, values_to = "enrichment" )
tail(med1)
med1=filter(med1, !is.na(enrichment))
colnames(med1) = c("Context","TSS_set","bin","enrichment")
med1 = mutate(med1, distance = bin*10-4000)
head(med1)
```

```{r}
med1$Context = factor(med1$Context, levels=c("White_Adi.","Beige_Adi."))
med1$TSS_set = factor(med1$TSS_set, levels = c("White_TSSs","Beige_TSSs","Non-sig_TSSs"))
ggplot(med1) + geom_line(aes(x=distance, y=enrichment, group=Context, color=Context, linetype=TSS_set), size=0.5) + 
  facet_wrap(~TSS_set) + theme_classic(base_size=22) +scale_color_manual(values= c("dodgerblue","orange","black")) +
  scale_linetype_manual(values=c("solid","solid","dashed"))+  coord_cartesian(y=c(0,5)) 
ggsave(file.path(HISTONES, "MED1","MED1_white_beige-10.profile.R.pdf"), width=15, height=5)

ggplot(med1) + geom_line(aes(x=distance, y=enrichment, group=TSS_set, color=TSS_set, linetype=TSS_set), size=0.5) + 
  facet_wrap(~Context) + theme_classic(base_size=22) +scale_color_manual(values= c("dodgerblue","orange","black")) +
  scale_linetype_manual(values=c("solid","solid","dashed"))+  coord_cartesian(y=c(0,5)) 
#+ geom_hline(aes(yintercept=0))
```