---
title: "PPARG bound promoters_take3"
output: html_document
date: "2023-11-16"
---

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
figs = "C:/Users/sarahhp/OneDrive - Universitetet i Oslo/Projects/rnaseq/beige_rnaseq_jul22/R/leafcutter/plots"
LEAF =  "C:/Users/sarahhp/OneDrive - Universitetet i Oslo/Projects/rnaseq/beige_rnaseq_jul22/31_leafcutter/promoter_binding/intersects"
```


```{r}
pparg_perc = read.delim(file.path(LEAF, "summary.txt"), header=F, sep=" ", col.names= c("bound_TSSs","intersect"))
pparg_perc = mutate(pparg_perc, tss_set=gsub("--.*", "", intersect), pparg_set = gsub(".*--","", gsub(".bed","", intersect)))
#head(pparg_perc)                        
total_tsss = read.delim(file.path(LEAF, "../line_summary.txt"), header=F, sep=" ", col.names= c("total_TSSs","bed_file"))
total_tsss$tss_set = gsub(".bed","",total_tsss$bed_file)
head(total_tsss)

pparg_perc = merge(pparg_perc, total_tsss, by="tss_set")
pparg_perc = mutate(pparg_perc, fraction=bound_TSSs/total_TSSs,
                    tss_set = gsub("lc_3db_", "",gsub( "_promoters\\.(uniq|merged)", "",tss_set)),
                    pparg_set = gsub("PPARgamma_hMADS_", "", pparg_set))
head(pparg_perc)
```


```{r}
pparg_perc$tss_set = factor(pparg_perc$tss_set, levels=c("white","beige","white_and_beige","not_sig"))
pparg_perc$pparg_set = factor(pparg_perc$pparg_set, levels=c("white","brite"))
ggplot(filter(pparg_perc,pparg_set!="total"), aes(x=tss_set, y=fraction, fill=tss_set)) + geom_bar(stat='identity') + 
  coord_cartesian(ylim=c(0,1)) + theme_classic(base_size=18) + 
  geom_text(aes(label=paste(round(fraction*100, 1), "%")),
            vjust=-1) + scale_fill_manual(values=c("#B8D7D6","#FCB54C","#8DA9D6","#D68FBE")) +
  labs(y="Proportion of PPARG-bound promoters") + facet_wrap(~pparg_set)
ggsave(file.path(figs,"PPARG_promoter_fraction.pdf"), width = 10, height=5)
```


